### ISSUE TITLE
Pool.GetOutputAmount failed

### ISSUE THREAD

**Issue by kibgzr** [daoleno/uniswapv3-sdk#1]
How to implement TickDataProvider?

**Comment by kibgzr** [comment]
So we need to know all Tick of Pool? How to request all ticks?

**Comment by daoleno** [comment]
* on chain -  [getPopulatedTicksInWord](https://github.com/Uniswap/v3-periphery/blob/main/contracts/interfaces/ITickLens.sol#L21-L25)
* off chain - [uniswap-v3-subgraph](https://thegraph.com/hosted-service/subgraph/uniswap/uniswap-v3)

**Comment by kibgzr** [comment]
I see this getPopulatedTicksInWord(address pool, int16 tickBitmapIndex) but I don't known tickBitmapIndex is what? Have any documents to help me understand this input value?

**Comment by daoleno** [comment]
Take a look at [TickBitMap](https://docs.uniswap.org/protocol/reference/core/libraries/TickBitmap).

I think you can iterate over all possible values of a 16 bit integer to get all active ticks.

**Comment by kibgzr** [comment]
So after fetching all ticks we can calculate the swap amount offline and only need re-fetch ticks when having a mint or burn event? That's true?

**Comment by daoleno** [comment]
With some slot information, yes. More detail [Creating the Pool Instance](https://docs.uniswap.org/sdk/guides/creating-a-pool#creating-the-pool-instance).
