### ISSUE TITLE
Token has no field or method Currency

### ISSUE THREAD

**Issue by Shuixingchen** [daoleno/uniswapv3-sdk#11]
github.com/daoleno/uniswapv3-sdk v0.3.0

DAI.Currency undefined (type *"github.com/daoleno/uniswap-sdk-core/entities".Token has no field or method Currency)

**Comment by daoleno** [comment]
We have refactored uniswap-sdk-core, but the documentation has not been updated.
Fixed in [v0.3.1](https://github.com/daoleno/uniswapv3-sdk/releases/tag/v0.3.1).
