### ISSUE TITLE
SwapCallParameters function problem

### ISSUE THREAD

**Issue by alikarimi999** [daoleno/uniswapv3-sdk#15]
Hi, I have a problem for swapping tokens 
this is my code 
```
import (
	"math/big"
	"time"

	"log"

	coreEntities "github.com/daoleno/uniswap-sdk-core/entities"
	"github.com/daoleno/uniswapv3-sdk/constants"
	"github.com/daoleno/uniswapv3-sdk/entities"
	"github.com/daoleno/uniswapv3-sdk/examples/helper"
	"github.com/daoleno/uniswapv3-sdk/periphery"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

var ETHRPC = "https://kovan.infura.io/v3/{{id}}"

func main() {
	client, err := ethclient.Dial(ETHRPC)
	if err != nil {
		log.Fatal(err)
	}
	wallet := helper.InitWallet({prv_key})
	if wallet == nil {
		log.Fatal("init wallet failed")
	}

	usdt := coreEntities.NewToken(42, common.HexToAddress("0x07de306ff27a2b630b1141956844eb1552b956b5"), 6, "USDT", "Tether USD")
	weth := coreEntities.NewToken(42, common.HexToAddress("0xd0a1e359811322d97991e03f863a0c30c2cf029c"), 18, "WETH", "Wrapped Ether")

	pool, err := helper.ConstructV3Pool(client, usdt, weth, uint64(constants.FeeMedium))
	if err != nil {
		log.Fatal(err)
	}

	//0.01%
	slippageTolerance := coreEntities.NewPercent(big.NewInt(1), big.NewInt(1000))
	//after 5 minutes
	d := time.Now().Add(time.Minute * time.Duration(15)).Unix()
	deadline := big.NewInt(d)

	// single trade input
	// single-hop exact input
	r, err := entities.NewRoute([]*entities.Pool{pool}, usdt, weth)
	if err != nil {
		log.Fatal(err)
	}

	swapValue := helper.FloatStringToBigInt("2", 6)
	trade, err := entities.FromRoute(r, coreEntities.FromRawAmount(usdt, swapValue), coreEntities.ExactInput)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%v %v\n", trade.Swaps[0].InputAmount.Quotient(), trade.Swaps[0].OutputAmount.Wrapped().Quotient())
	params, err := periphery.SwapCallParameters([]*entities.Trade{trade}, &periphery.SwapOptions{
		SlippageTolerance: slippageTolerance,
		Recipient:         wallet.PublicKey,
		Deadline:          deadline,
	})
	if err != nil {
		log.Fatal(err)
	}

	to := common.HexToAddress("0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45")

	tx, err := helper.TryTX(client, to,
		big.NewInt(0), params.Calldata, wallet)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(tx.Hash().String())

}
```
and it returns me `The execution failed due to an exception.` this error.
so I searched about this error and understood that one of the main reasons is corrupted input data
so instead of using SwapCallParameters I swapped with uniswap web application and extracted its input data https://kovan.etherscan.io/tx/0xd9ba16700e54348c0e9648e4eeec7160ec523a92bff8baca237687ea86a5300c
and used it in code and it generate this transaction successfully https://kovan.etherscan.io/tx/0x360d93ba9ba7f39acf5ae7931528e4ecb8666fc6fe1b4213e513abea826571af
so I think maybe there is a problem with this function but I can't debug it
i appreciate any help

**Comment by daoleno** [comment]
[0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45](https://kovan.etherscan.io/address/0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45#code) is a [SwapRouter02](https://github.com/Uniswap/swap-router-contracts/blob/main/contracts/SwapRouter02.sol) contract. JS/GO V3-SDK does not support this. But [@uniswap/smart-order-router](https://docs.uniswap.org/sdk/guides/liquidity/swap-and-add) can do this.

You can try [SwapRouter](https://github.com/Uniswap/v3-periphery/blob/main/contracts/SwapRouter.sol) contract. I didn't test on Kovan, [Goerli](https://goerli.etherscan.io/tx/0x75a2d95e12a28a6fa942e1e4de483dae8c0a49fd5529507195857193655dc5d1) is ok.

More specifically, in the `ExactInput` case, [SwapRouter02](https://etherscan.io/address/0x075b36de1bd11cb361c5b3b1e80a9ab0e7aa8a60#code#F15#L10) and [SwapRouter](https://etherscan.io/address/0xe592427a0aece92de3edee1f18e0157c05861564#code#F5#L15) have different parameters for the `function exactInputSingle`.

```solidity
# SwapRouter02
struct ExactInputSingleParams {
        address tokenIn;
        address tokenOut;
        uint24 fee;
        address recipient;
        uint256 amountIn;
        uint256 amountOutMinimum;
        uint160 sqrtPriceLimitX96;
 }

# SwapRouter
struct ExactInputSingleParams {
        address tokenIn;
        address tokenOut;
        uint24 fee;
        address recipient;
        uint256 deadline; # <------
        uint256 amountIn;
        uint256 amountOutMinimum;
        uint160 sqrtPriceLimitX96;
}
```

**Comment by alikarimi999** [comment]
thanks for your help 
so I replaced `0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45` with `0xe592427a0aece92de3edee1f18e0157c05861564`  and still get the same error
but in rinkbey get this error `execution reverted: STF` should I change the network again or it's something else?

**Comment by daoleno** [comment]
Make sure you approve the token.

**Comment by alikarimi999** [comment]
can i do it with this package???

**Comment by daoleno** [comment]
The SDK can't do that. You need to call the `Approve` function in the erc20 contract. [Ethereum Development with Go[Smart Contracts]](https://goethereumbook.org/en/smart-contracts/) is a good place to start.
