### ISSUE TITLE
Output amount is not calculated correctly in some cases

### ISSUE THREAD

**Issue by andrewelkin** [daoleno/uniswapv3-sdk#16]
Hi guys, first of all, thank you for the great library and the effort to maintain it! 

_Issue:_

in some cases pool.GetOutputAmount()  (and Pool.swap() )  is not calculating output amount correctly with ExactInput option

_Suspected case:_

when current tick of the pool is negative

_How to reproduce:_

try to form a swap tx for UNI/WETH/30 pool with exact input WETH amount (0.1 in my case). Current tick for the pool is something close to -55200.
Check the value returned from pool.GetOutputAmount() (called from FromRoute(...,coreEntities.ExactInput) ) .

**Comment by daoleno** [comment]
Hi. Can you provide a full example so that I can easily reproduce the problem?

**Comment by andrewelkin** [comment]
> Hi. Can you provide a full example so that I can easily reproduce the problem?

Hey. Sure thing! I'll try to make a code snippet/example to have it rectified.
