### ISSUE TITLE
Implement atomic swaps

### ISSUE THREAD

**Issue by alienatorZ** [daoleno/uniswapv3-sdk#3]
This library could use the swap and add functionality found here: [https://docs.uniswap.org/sdk/guides/liquidity/swap-and-add#fetching-calldata-from-routetoratio](url)

**Comment by daoleno** [comment]
Thanks for the suggestion.
But the goal of this project is to be consistent with the functionality of https://github.com/Uniswap/v3-sdk.
Maybe we can create another `smart-order-router` to do this.

**Comment by alienatorZ** [comment]
Ok Thank you!
