### ISSUE TITLE
abi can not pack (Standard)PermitArguments

### ISSUE THREAD

**Issue by andrewelkin** [daoleno/uniswapv3-sdk#5]
```abi: cannot use uint as type uint8 as argument ```
when calling abi.Pack("selfPermit", token.Address, options.Amount, options.Deadline, options.V, options.R, options.S) in selfpermit.go

**Comment by daoleno** [comment]
Thanks. Fixed [v0.2.1](https://github.com/daoleno/uniswapv3-sdk/releases/tag/v0.2.1)
